# Generated by Django 3.2.3 on 2021-06-12 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='fotos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rayoMakween.categoria')),
            ],
        ),
    ]
