# Generated by Django 3.2.3 on 2021-06-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0002_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='imagen',
        ),
    ]
