# Generated by Django 3.2.3 on 2021-06-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0003_remove_auto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
