# Generated by Django 3.2.3 on 2021-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0007_alter_auto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='anno_vehiculo',
            field=models.IntegerField(null=True),
        ),
    ]
