# Generated by Django 3.2.3 on 2021-06-15 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0008_auto_anno_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
