# Generated by Django 3.2.3 on 2021-06-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0009_auto_20210615_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='usuario',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
